# Generated by Django 3.2.11 on 2022-04-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_rank_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
