# Generated by Django 3.2.11 on 2022-04-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_retirementreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirementreason',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
