# Generated by Django 3.2.11 on 2022-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_retirementreason_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sender_id', models.CharField(default='GHPOLPEN', max_length=100, unique=True)),
            ],
        ),
    ]
