# Generated by Django 3.2.11 on 2022-04-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_sysconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysconfig',
            name='send_sms',
            field=models.BooleanField(default=True),
        ),
    ]
