# Generated by Django 3.2.11 on 2022-04-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_sysconfig_send_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='sms_sender_id',
            field=models.CharField(default='GHPOLPEN', max_length=11, unique=True),
        ),
    ]
