# Generated by Django 3.2.11 on 2022-03-13 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('retiring_date', models.DateField()),
                ('reason', models.TextField()),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account', models.CharField(max_length=50)),
                ('last_station', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('contact_address', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
