# Generated by Django 3.2.11 on 2022-03-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
