# Generated by Django 3.2.11 on 2022-03-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220315_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_change_status', 'Change status'),)},
        ),
    ]
