# Generated by Django 3.2.11 on 2022-03-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220316_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('can_review_application', 'Change status'), ('can_generate_letter', 'Generate Award Letter from Application'))},
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/applications'),
        ),
    ]
