# Generated by Django 3.2.11 on 2022-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220318_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/signature'),
        ),
    ]
