# Generated by Django 3.2.11 on 2022-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_application_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(null=True, upload_to='uplodas/documents'),
        ),
    ]
