# Generated by Django 3.2.11 on 2022-03-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_applicationdocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.ImageField(null=True, upload_to='uplodas/documents'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='dashboard.applicationdocumenttype'),
        ),
    ]
