# Generated by Django 3.2.11 on 2022-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220320_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocumenttype',
            name='codename',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationdocumenttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
