# Generated by Django 3.2.11 on 2022-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20220320_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocumenttype',
            name='multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applicationdocumenttype',
            name='codename',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
