# Generated by Django 3.2.11 on 2022-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20220320_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='requested_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('request_changes', 'request_changes'), ('processing', 'processing')], default='draft', max_length=50),
        ),
    ]
