# Generated by Django 3.2.11 on 2022-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
