# Generated by Django 3.2.11 on 2022-04-22 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0024_auto_20220421_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='inititated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_sms', to=settings.AUTH_USER_MODEL),
        ),
    ]
