# Generated by Django 3.2.11 on 2022-04-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20220422_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPensionableEmolumentDrawnBeforeRetirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=100)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('emolument', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('controller_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_pensionable_emoluments_drawn_before_retirement', to='dashboard.controllerform')),
            ],
        ),
    ]
