# Generated by Django 3.2.11 on 2022-04-22 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_nopayleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('controller_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_breaks', to='dashboard.controllerform')),
            ],
        ),
    ]
