# Generated by Django 3.2.11 on 2022-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_officeparticulars_controller_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeparticulars',
            name='if_pensionable',
            field=models.CharField(max_length=200, verbose_name='If Pensionable'),
        ),
    ]
