# Generated by Django 3.2.11 on 2022-04-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_application_open_vote_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='open_vote_date',
        ),
        migrations.AddField(
            model_name='controllerform',
            name='open_vote_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
