# Generated by Django 3.2.11 on 2022-04-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20220424_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOpenVoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('controller_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_open_vote_service', to='dashboard.controllerform')),
            ],
        ),
    ]
