# Generated by Django 3.2.11 on 2022-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_alter_sysconfig_sms_sender_id'),
        ('dashboard', '0038_paidopenvoteservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.rank'),
        ),
        migrations.AlterField(
            model_name='paidopenvoteservice',
            name='controller_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_open_vote_services', to='dashboard.controllerform'),
        ),
        migrations.AlterField(
            model_name='pensionableemolumentdrawnbeforeretirement',
            name='controller_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_pensionable_emoluments_drawn_before_retirements', to='dashboard.controllerform'),
        ),
    ]
